### ISSUE TITLE
[enhancement label] What is ThroughputMode is provisioned?

### ISSUE THREAD

**Issue by secure-clouds** [1Strategy/efs-starter-template#1]
In case the ThroughputMode is set to provisioned in the paramters. The "ProvisionedThroughPutInMibps" will need to be set. 
Any way this dynamic behavior can be handled?

**Comment by jiravani** [comment]
This should now be addressed. Thank you for the feedback.

**Comment by avi26-git** [comment]
That was prompt! 👍 The issue still remains open though. If I were to use this template, the ThroughputMode  as Provisioned would work fine. The trouble then is the the Bursted mode. Now, the template can't be deployed because the ProvisionedThroughPutInMibps would be empty. (The template won't even reach "AWS::NoValue")

**Comment by secure-clouds** [comment]
> This should now be addressed. Thank you for the feedback.
That was prompt! 👍 The issue still remains open though. If I were to use this template, the ThroughputMode as Provisioned would work fine. The trouble then is the the Bursted mode. Now, the template can't be deployed because the ProvisionedThroughPutInMibps would be empty. (The template won't even reach "AWS::NoValue")
